api-referrence.md, sso_tokens_create.md
Add document of /api/v1/sso_tokens
=> Add SSO tokens document

README.md, api-referrence.md
Apply the new inquiry address `pfm-api@moneyforward.co.jp` in whole of documents.
=> Change email address for inquiry

user_show.md
So-net 対応
https://mf.esa.io/posts/26240#4-0-0 の 1
=> Add calc st day to /user

categories_index.md
=> /api/v1/transactions/categories

transactions_create.md, transactions_update.md
=> /api/v1/transactions/:id

transaction_histories_index.md, transaction_summaries_index.md
- `/api/v1/derived/transaction_summaries`
- `/api/v1/derived/transaction_histories`
=> Add /derived/transaction

api-referrence.md
* Userinfoを分けて、スコープについて記述した。
* 「いずれかのの」という間違いを直した。
* 空白の中にへんなキャラクタが混ざっていたので半角空白に直した。
* HTMLメソッドが２つある場合の書き方を「または」を使う書き方に統一した。
=> Improve userinfo, etc.

api-referrence.md, profile_show.md
* なるはや
* GET /api/v1/profile を追加した。
=> GET /api/v1/profile の追加

api-referrence.md
* いますぐ
* https://github.com/moneyforward/api-doc/pull/27 での修正漏れ
=> 'api/v1/derived/transaction_summaries' に 'category_size' パラメーターを足した

user_asset_histories_index.md, user_asset_histories_show.md, user_assets_show.md, user_show.md
* いつでも
* ’例' というセクションを付けるのを忘れている箇所があった。セクションを足した。
=> '例' というセクションがなかったのを足す

transactions_create.md, transactions_update.md
* なるはや
* 'transactions_create' と 'transactions_update' の例に間違いがあった。これを正す。
=> 'transactions_create' と 'transactions_update' の例を正す

token.md
=> Fix. expの記述

token.md
=> Fix typographical mistake

user_show.md
いつでも
`user_show` の出力の説明をより正確にした。
=> More accurate explanation on 'user_show' output

README.md, sso_tokens_create.md
=> Fix mistakes related SSO token pages

sso_tokens_create.md
=> Fix example

services_index.md
こちらのPRがマージされたらどキュメントを追加する
https://github.com/moneyforward/pfm_web/pull/14127
=> biz_flagを追加した

authorize.md
間違った文面を放置していました。応答が得られるのでなく、リダイレクトされ、クエリーパラメーターが与えられます。
さらに改良できるなら、適当に変えて下さい。
=> 間違っていた記述の修正

accounts_show.md
https://github.com/moneyforward/pfm_web/blob/release/app/controllers/api/v1/accounts_controller.rb#L21
`Api::V1::AccountDecorator.json_option_minus` なので
=> remove asset sum from account show

README.md, transactions_recent.md
=> 新着明細取得APIの追加

README.md, accounts_suspend.md
=> 口座一時停止APIのドキュメントの追加
